baseURL = 'https://blog.yixboost.dev/'
languageCode = 'en-us'
title = 'Yixboost Blog'
theme = "nightfall"

enableRobotsTXT = true

[pagination]
pagerSize = 5

[params]
user = "root"
hostname = "blog.yixboost.dev"
displayDateFormat = "02.01.2006"
# Global metadata display settings
showMetadata = true      # Master switch for all metadata display (default: true)
showPublishedDate = true # Show published date on post page (default: true)
showReadingTime = true   # Show reading time on post page (default: true)
showTags = true          # Show tags on post page (default: true)
showAuthors = true       # Show authors on post page (default: true)
showCategories = true    # Show categories on post page (default: true)

[params.author]
name = "Yixboost"
email = "https://link.yixboost.dev/contact"
avatarFirst = false

[[params.social]]
key = 0
name = "GitHub"
url = "https://link.yixboost.dev/github"
#icon = "fa-brands fa-github"  # Add link to your icon font to `layouts/partials/custom-head.html`
#target = "_blank" # Defines your target option in a-href. _blank for a new Tab for example.
#aria = "GitHub Profile" # Define the aria label for accessibility like page reader - this is better for your SEO

[[params.social]]
key = 1
name = "Email"
url = "https://link.yixboost.dev/contact"

[params.styles]
color = "green"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"

[outputs]
home = ["HTML","RSS","JSON"]

[caches.images]
dir = ":cacheDir/images"
